//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yesil.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCard
    {
        public int OrderCardId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string HolderName { get; set; }
        public string Number { get; set; }
        public Nullable<int> ExpirationYear { get; set; }
        public Nullable<int> ExpirationMonth { get; set; }
        public Nullable<int> Ccv { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
